Better config options and improved POSIX compatibility

diff --git a/shell_common b/shell_common
--- a/shell_common
+++ b/shell_common
@@ -5,17 +5,24 @@
 #
 # Latest copy always here: https://github.com/mattsday/dotfiles/
 
-# Set some local utilities as default (this must be top of this file)
+# Execute any local bourne script config - local config should go in _local below:
+if [ -f "$HOME/.shell_common_config" ]; then
+	. "$HOME/.shell_common_config"
+fi
+
+# Set some local utilities as default (this must be top of this file after local config)
 if [ -d /usr/local/bin ]; then
 	# Affix /usr/local/bin to PATH as homebrew zsh doesn't do this for some
 	# reason
-	export PATH=/usr/local/bin:$PATH
+	PATH=/usr/local/bin:$PATH
+	export PATH
 
 	# Create an update alias if homebrew is installed
 	if [ -x /usr/local/bin/brew ]; then
 		alias update="brew update; brew upgrade; brew cleanup; brew doctor"
 		# Opt out of homebrew fucking analytics
-		export HOMEBREW_NO_ANALYTICS=1
+		HOMEBREW_NO_ANALYTICS=1
+		export HOMEBREW_NO_ANALYTICS
 	fi
 fi
 
@@ -35,21 +42,27 @@ fi
 
 # Always prefer vim to alternatives
 if command -v vim > /dev/null 2>&1; then
-	export VISUAL=$(command -v vim)
-	export USE_EDITOR=$VISUAL
-	export EDITOR=$VISUAL
+	VISUAL=`command -v vim`
+	USE_EDITOR=$VISUAL
+	EDITOR=$VISUAL
+	export VISUAL USE_EDITOR EDITOR
 	# Some systems are cruel and have vi + vim installed side-by-side
-	alias vi=$VISUAL
+	# As some of these systems are too ancient to even support alias,
+	# set vi as a function:
+	vi () {
+		$VISUAL $*
+	}
 fi
 
 # Set less as the default pager
 if command -v less > /dev/null 2>&1; then
-	export PAGER=$(command -v less)
+	PAGER=`command -v less`
+	export PAGER
 fi
 
 # If we can sudo dodo!
 if [ -x /usr/bin/sudo ] || [ -x /usr/local/bin/sudo ]; then
-    # Alias sudo so it can be expanded with aliases (e.g. sudo ll)
+	# Alias sudo so it can be expanded with aliases (e.g. sudo ll)
 	alias sudo='sudo '
 	# Debian based systems
 	if [ -x /usr/bin/apt-get ]; then
@@ -106,7 +119,8 @@ fi
 alias grep='grep --color=auto'
 alias egrep='egrep --color=auto'
 alias fgrep='fgrep --color=auto'
-export GREP_COLORS="ms=01;32:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36"
+GREP_COLORS="ms=01;32:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36"
+export GREP_COLORS
 
 # Meh, shit happens:
 alias 'cd..=cd ..'
@@ -134,11 +148,13 @@ gf() {
 # These affect most systems and are (usually) harmless if run without...
 
 # Sets ls and various commands to use yyyy-mm-dd as the date format
-export TIME_STYLE="long-iso"
+TIME_STYLE="long-iso"
+export TIME_STYLE
 
 # OS X ls colouring (non-gnu ls)
-export CLICOLOR="yes"
-export LSCOLORS="gxhxfxcxcxdxcxcxcxgxgx"
+CLICOLOR="yes"
+LSCOLORS="gxhxfxcxcxdxcxcxcxgxgx"
+export CLICOLOR LSCOLORS
 
 # Do we need to load proxy settings?
 if [ -f "$HOME/.enable_proxy" ]; then
@@ -155,23 +171,29 @@ fi
 # =====================
 # Checks about terminal colour support
 
-# Test for number of colours
-colours=$(tput colors 2> /dev/null)
-
-# If tput errors out then try and fix...
-if [ $? -gt 0 ]; then
-	# If it's reporting as a 256-colour term try changing to just an xterm
-	[ "$TERM" = "xterm-256color" ] && export TERM=xterm
-	colours=$(tput colors 2> /dev/null)
-	# If that still fails then disable colour
+# Check if colours are forced-enabled/disabled:
+if [ -f "$HOME/.enable_shell_colour" ]; then
+	colours=256
+elif [ -f "$HOME/.disable_shell_colour" ]; then
+	colours=7
+else
+	# Test for number of colours
+	colours=`tput colors 2> /dev/null`
+	# If tput errors out then try and fix...
 	if [ $? -gt 0 ]; then
-		colours=7
+		# If it's reporting as a 256-colour term try changing to just an xterm
+		[ "$TERM" = "xterm-256color" ] && TERM=xterm && export TERM
+		colours=`tput colors 2> /dev/null`
+		# If that still fails then disable colour
+		if [ $? -gt 0 ]; then
+			colours=7
+		fi
 	fi
 fi
 
-# Check if colour is disabled manually
-if [ -f ~/.disable_shell_colour ]; then
-	colours=7
+# Execute any local bourne scripts:
+if [ -f "$HOME/.shell_common_local" ]; then
+	. "$HOME/.shell_common_local"
 fi
 
-# vim: syntax=zsh
+# vim: syntax=sh
